<?php
/**
 * User        : 青草根
 * Email       : caimh0223@163.com
 * Blog        : http://52qcg.cn
 * Date        : 2019.10.31
 * Time        : 12:40
 * Description : ********
 */
namespace app\index\controller;
use app\index\service\ArticleService;
use think\Controller;

class Base extends Controller
{
    protected $_service =null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_service= new ArticleService();
        $res  = $this->_service->base();
        $this->assign('nav',$res['nav']);
        //var_dump($res['nav']);exit;
        $this->assign('hotArt',$res['hot']);
        $this->assign('suggestArt',$res['suggest']);
        $this->assign('newArt',$res['new']);
        $this->assign('tags',$res['tags']);
        $this->assign('imgArt',$res['img']);
        $this->assign('bread',$res['bread']);
        $this->assign('config',config('siteconfig'));
        //var_dump($res['nav']);exit;
    }
}