<?php
/**
 * User        : 青草根
 * Email       : caimh0223@163.com
 * Blog        : http://52qcg.cn
 * Date        : 2019.11.06
 * Time        : 8:14
 * Description : ********
 */
namespace app\admin\controller;

use app\admin\service\AdvGroupService;
use app\admin\service\AdvService;
use app\common\model\AdvGroupModel;

class Adv extends Base
{
    public function _initialize()
    {
        $this->_service=new AdvService();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $data = [];
        if(request()->isPost())
        {
            $data = input('post.');
            //处理数据逻辑
        }
        $resData = $this->_service->index($data);
        $advGroupService = new AdvGroupService();
        $advGroup = $advGroupService->index();
        $this->assign('resData',$resData);
        $this->assign('advGroup',$advGroup);
        return view();
    }

    public function add()
    {
        $template = 'add';
        if(request()->isPost())
        {
            return $this->_service->add();
        }
        if(request()->route('id')>0)
        {
            $template = 'edit';
        }
        $advRes = $this->_service->add();
        $advGroupService = new AdvGroupService();
        $advGroup = $advGroupService->index();
        $this->assign('groupData',$advGroup);
        $this->assign('advRes',$advRes);
        return view($template);
    }

    public function del()
    {
        return $this->_service->del();
    }
}