<?php
/**
 * Created by PhpStorm.
 * User: Kevin
 * Date: 2018/8/2
 * Time: 21:54
 */
namespace app\admin\controller;
use think\Controller;
use think\Db;
use app\admin\service\IndexService;
class Index extends  Base
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        //赋值service
        //$serviceName = ucfirst($controller).'Service';
        $this->_service = new IndexService();
    }

    /**
     * 框架页面
     * @return mixed
     */
    public function index()
    {
        return $this->fetch('/index');
    }

    /**
     * 首页
     * @return mixed|\think\response\Json
     */
    public function indexPage()
    {
        return $this->fetch('index/index');
    }

    /**
     * 清除缓存
     */
    public function clear() {
       return $this->_service->clear();
    }

    public function webuploader(){
        return $this->fetch('/webuploader');
    }
}